import type React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import ClientLayout from "./clientLayout";
import { SidebarProvider } from "@/components/ui/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "StartUp-SL",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  notifications?: any[];
  unreadCount?: number;
}

export default function RootLayout({
  children,
  notifications = [],
  unreadCount = 0,
}: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientLayout notifications={notifications} unreadCount={unreadCount}>
          <SidebarProvider>
            {children}
            <Toaster />
          </SidebarProvider>
        </ClientLayout>
      </body>
    </html>
  );
}
